name: bridgecrew-scanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Scan IaC directory
        id: Bridgecrew-directory-scanner
        uses: bridgecrewio/bridgecrew-action@master
        with:
          directory: "terraform"
          soft_fail: true

      - name: Scan IaC file
        id: Bridgecrew-file-scanner
        uses: bridgecrewio/bridgecrew-action@master
        with:
          file: "./terraform/db-app.tf"
          api-key: ${{ secrets.API_KEY }}